jwt:
  access_expiration_time: 10
  refresh_expiration_time: 60
  secret: jwt-secret
log:
  level: fatal
db:
  type: mongodb
  mongodb:
    database: sigma-music
    user: root
    password: password
    url: mongodb://mongodb:27017
  postgres:
    user: sigma
    password: sigma
    host: db
    port: 5432
    name: sigmamusic