services:
  - name: docker:dind
    command: ["--tls=false"]

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal"
  ALLURE_OUTPUT_PATH: "/builds/mta21u184/sigma-music-test"

stages:
  - unit-test
  - integration-test
  - e2e-test

unit:
  stage: unit-test
  image: golang:1.22
  script: 
    - echo TESTTEST=1 > .env
    - go test -shuffle on ./internal/service/test/unit ./internal/adapters/repository/postgres/test/ -v --parallel 4
  after_script:
    - if [[ $CI_JOB_STATUS != "success" ]]; then echo TEST_FAILED=1 > .env; else TEST_FAILED=0 > .env; fi
  artifacts:
    paths:
      - allure-results
    reports:
      dotenv: .env
  rules:
    - when: always

integration:
  stage: integration-test
  image: golang:1.22
  script: 
    - printenv
    - go test -shuffle on ./internal/service/test/integration/ -v --parallel 4
  artifacts:
    paths:
      - allure-results
  rules:
    - when: always

e2e:
  stage: e2e-test
  image: golang:1.22
  script: go test -shuffle on ./internal/service/test/e2e/ -v
  artifacts:
    paths:
      - allure-results
  rules:
    - when: always
