services:
  - name: docker:dind
    command: ["--tls=false"]

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal"
  ALLURE_OUTPUT_PATH: "/builds/mta21u184/sigma-music-test"

stages:
  - report history
  - unit-test
  - integration-test
  - e2e-test

collect_report_history:
  stage: report history
  script:
    - echo $CI_COMMIT_BRANCH
    - echo $REPORT_TOKEN
    - 'curl --header "PRIVATE-TOKEN: $REPORT_TOKEN" --location "https://git.iu7.bmstu.ru/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/$CI_COMMIT_BRANCH/download?job=e2e" --output artifacts.zip' 
    - unzip artifacts.zip
    - ls
  allow_failure: true
  artifacts:
    paths:
      - ./allure-results
    expire_in: 1 day
  rules:
    - when: always

unit:
  stage: unit-test
  image: golang:1.22
  script: go test -shuffle on ./internal/service/test/unit 
    ./internal/adapters/repository/postgres/test/ -v --parallel 4
  artifacts:
    paths:
      - allure-results
  rules:
    - when: always

integration:
  stage: integration-test
  image: golang:1.22
  script: go test -shuffle on ./internal/service/test/integration/ -v --parallel 4
  artifacts:
    paths:
      - allure-results
  rules:
    - when: always

e2e:
  stage: e2e-test
  image: golang:1.22
  script: go test -shuffle on ./internal/service/test/e2e/ -v
  artifacts:
    paths:
      - allure-results
  rules:
    - when: always
