jwt:
  access_expiration_time: 10
  refresh_expiration_time: 60
  secret: jwt-secret
log:
  level: info
db:
  type: postgres
  postgres:
    user: sigma
    password: sigma
    host: postgres
    port: 5432
    name: sigmamusic
